### ISSUE TITLE
App crashes after backing out of github

### ISSUE THREAD

**Issue by Invalid-Signal** [AxelFougues/ZINC-public-resources#2]
**Describe the bug**
After clicking the button to read the GitHub help page, I try to go back but the app crashes.

**Expected behavior**
Should go straight back to last page in the app.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9 Pro
 - OS: Android 13
 - Browser: Chrome

**Comment by AxelFougues** [comment]
Do you go back with the android back button or the "x" at the top of the webview?

**Comment by Invalid-Signal** [comment]
> Do you go back with the android back button or the "x" at the top of the webview?

I use the back button. Just tested the "x" and the burger button in the top right is kind of sitting under the "x" so I accidentally hit the burger/menu button instead.
![Screenshot_2023-08-03-22-52-15-01_2cd11edca93eb097e1f30abe17fb9d1e.jpg](https://github.com/AxelFougues/ZINC-public-resources/assets/141380678/63ab128b-32a4-42bc-acc1-95a989397ab4)

Edit: The overlapping looks worse on my phone than the screenshot, though that might be my giant OtterBox phone case causing my issue with the overlap lol

**Comment by AxelFougues** [comment]
Fix Android back button functionality
Closing priority: Webview > Feature > App
f9c2eaf
