### ISSUE TITLE
Wrong date being set on upgrade modification 

### ISSUE THREAD

**Issue by AxelFougues** [AxelFougues/ZINC-public-resources#25]
I just entered my 2 upgrades and edited their location and install dates. I clearly selected October 23 as the install date, but the app saved it as 10/22/2023. I just went back in and changed my click on the calendar popup to October 24, and it saved the date as 10/23/2023.

Reported by XC-108, DT forum

**Comment by aoxhwjfoavdlhsvfpzha** [comment]
Having the same issue, unable to change my install dates from 4/6/2025
