### ISSUE TITLE
A few small bugs

### ISSUE THREAD

**Issue by duckydisaster** [AxelFougues/ZINC-public-resources#5]
### **Issue 1: Default Checkbox State for Implant Categories**

Description: When adding a product, all the implant category checkboxes are checked by default, which may lead to unintentional selections.

Steps to Reproduce:

    Go to the "Product" section, press "+"
    Observe that all implant category checkboxes are pre-checked.

Expected Behavior: The checkboxes for implant categories should be initially unchecked, allowing the user to select the relevant categories.

### **Issue 2: Missing "Save" Button for Upgrade Editing**

Description: When editing an upgrade, there is no "Save" button. Instead, users need to press the 'X' button to close the editing window, which can be confusing.

Steps to Reproduce:

    Go to the "My Upgrade" section, go to "Edit upgrade"
    Observe that there is no explicit "Save" button.

Expected Behavior: There should be a clear "Save" button to confirm and save the changes made to an upgrade.

### **Issue 3: Lack of Image Caching for Self-Added Products**

Description: The images for self-added products are not cached, resulting in slower loading times, especially on slow internet connections.

Steps to Reproduce:

    Add a self-created product.
    Reload the page or navigate away and return.
    Observe that the product image takes a while to load.

Expected Behavior: Images for self-added products should be cached to improve page loading performance.

### **Issue 4: Accidental Removal of Upgrades**

Description: The "remove upgrade" button is easily pressed by accident, and there is no confirmation dialog to confirm the deletion of the upgrade.

Steps to Reproduce:

    Go to the upgrades section, click "Edit upgrade" and scroll down
    Click the "remove upgrade" button.

Expected Behavior: There should be a confirmation dialog asking the user to confirm the deletion of the upgrade.

### **Issue 5: Overlapping Default Image and Symbol**

Description: The default image overlaps with a symbol in the bottom-right corner (as shown in the provided screenshot).

Steps to Reproduce:

    Create a new product.

Expected Behavior: The default image should not overlap with any symbols.

### **Issue 6: Missing "About" Section for App Version Information**

Description: There is no "About" section where users can view the installed app version, which can be important for troubleshooting and support purposes.

Steps to Reproduce:

    Navigate through the app interface.
    Look for an "About" or "Version" section.

Expected Behavior: There should be an "About" section that displays information about the installed app version.

Additional Notes:

    Screenshots have been provided for Issue 5.
    This report has been submitted on 21.10.23.
    Device Information: [star2lte SM-G965F Android 11]
    Zinc version 0.1.2.8.2

**Comment by duckydisaster** [comment]
![photo_5305365740183998616_y](https://github.com/AxelFougues/ZINC-public-resources/assets/148643305/0d114cd1-94a0-4112-b45a-064d42df7ea4)

**Comment by AxelFougues** [comment]
Issue 1, fixed

**Comment by AxelFougues** [comment]
Issue 2, fixed

**Comment by AxelFougues** [comment]
Issue 3, won't fix now. Moved to its own ticket

**Comment by AxelFougues** [comment]
Issue 4, fixed with "Hold buttons" for upgrades and products as well.

**Comment by AxelFougues** [comment]
Issue 5, fixed.

**Comment by AxelFougues** [comment]
Issue 6, fixed with version display.
